### ISSUE TITLE
 Error: System does not have required utilities... 

### ISSUE THREAD

**Issue by dr4lekhine** [grahamhelton/dredge#1]
Hello,

First of all, kudos, and thank you for this interesting tool! :)

When I try to test it in a Rocky Linux 9.3 (Blue Onix), I´m receiving the error: "**_Error: System does not have required utilities.._**."

Can you help with this?. All the tools are installed (checked with yum), and also seems to be on $PATH variable. Attaching some screenshots here:
[Screenshots_errors.zip](https://github.com/grahamhelton/dredge/files/14781792/Screenshots_errors.zip)

Same issue also happens with the root user directly.

Thanks in advance.

Regards.

**Comment by grahamhelton** [comment]
Accidentally pushed a version I was debugging with. Should be fixed now.
