### ISSUE TITLE
Issue getting wordlist path when executed outside script directory

### ISSUE THREAD

**Issue by opabravo** [grahamhelton/dredge#5]
## Issue screenshot

![image](https://github.com/user-attachments/assets/df7a1716-3718-41c4-8926-174d69d1aff6)

## After fixing it

- Commit : e4e8f3ef96cc1f9a0ba9d7c8ed993142d51d125a

![image](https://github.com/user-attachments/assets/ef8b14f1-11cf-4867-b08b-ebb883a9c0a9)

**Comment by grahamhelton** [comment]
Fixed in e4e8f3ef96cc1f9a0ba9d7c8ed993142d51d125a
